### ISSUE TITLE
Boot from SDCard

### ISSUE THREAD

**Issue by fxsheep** [WOA-Project/Lumia950XLPkg#27]
This AArch64 uefi can't detect external sdcard.However the original arm32 one can.Will it possible to add sd driver and boot from sdcard?

**Comment by gus33000** [comment]
wimboot is the name for a technology working with file diffing against a main install.wim located in the recovery partition. It requires disk access.

VHD boot requires disk access as well.

**Comment by fxsheep** [comment]
@b-man there's a quick way to verify the last one, just boot Windows RT (coz it's 32bit and can be loaded by wp uefi) on sdcard with sd controller related drivers set to load on boot.

**Comment by imbushuo** [comment]
Linux is more likely utilizing SD card boot.

@b-man Stock Qualcomm UEFI does expose SD card with the protocol, but it will bugcheck later when `ExitBootServices` is called - SDBus.sys does not support booting from it (at least right now). BTW, it refused to boot from eMMC HS400 too (I configure eMMC to HS200 here). I have not expose it in this implementation yet.

The controller has a dependency to TLMM GPIO (to indicate SD card presence). It may be possible to remove the detection and report it as always present (the patch for DB410c booting from LK did so). I have not tried it yet.

**Comment by imbushuo** [comment]
MicroSD is populated in UEFI and should be usable. The UI for boot device selection (which will be tracked in a separate issue) has not yet been implemented.
