### ISSUE TITLE
Can't boot into Windows (INACCESSIBLE_BOOT_DEVICE)

### ISSUE THREAD

**Issue by DremOSDeveloperTeam** [WOA-Project/Lumia950XLPkg#48]
After deploying the latest version of Windows, it brings up a BSOD that has the error "INACCESSIBLE_BOOT_DEVICE"... any suggestions?
[Image](https://imgur.com/a/g06YE7j)

Edit: I just remembered I can use older versions of windows, so I'm trying 1803
Edit 2: 1803 doesn't work either, but I get a different error: SDBUS_INTERNAL_ERROR
Edit 3: After rebooting that error seemed to fix itself. It's now at "Getting Devices Ready". I guess I'll just update it to 1903 when it gets fully set up.
Edit 4 ugh: I keep getting SDBUS_INTERNAL_ERROR
Edit 5: I guess it only wants to start when it wants to. Works now, I guess I just have to restart it about 5 or 6 times if my device decides it has better things to do than, yn, work

**Comment by feherneoh** [comment]
just deployed a fresh 1903, booted fine
