### ISSUE TITLE
Configure UC120 on non-Hapanero devices

### ISSUE THREAD

**Issue by Googulator** [WOA-Project/Lumia950XLPkg#50]
The Lumia 950 and XL have a Lattice UC120 chip for USB-C negotiation and USB-PD.
Right now, it appears that this chip loses its configuration at some point during boot (likely when the SoC is switched to 64-bit mode), requiring a reupload of the bitstream.

The bitstream upload protocol for the UC120 uses a modified SPI bus that the MSM SPI controllers don't support, thus requiring GPIO bitbanging. Unfortunately Windows' GPIO stack isn't fast enough to upload the whole 72KB bitstream over bitbanged SPI (~1KHz is the maximum achievable), so this needs to be done in the UEFI instead.

**Comment by imbushuo** [comment]
Work started in https://github.com/WOA-Project/Lumia950XLPkg/tree/lattice-fpga.

**Comment by imbushuo** [comment]
Resolved via #54.
