### ISSUE TITLE
Quick Rundown

### ISSUE THREAD

**Issue by 0x0000ff** [WOA-Project/Lumia950XLPkg#71]
Apologies if this isn't the right place to enquire.

I'd just like to know how you have managed to run a custom boot-oader on these devices, assuming that Qualcom's boot process is the same as that on their android counterparts. 

I've been looking for a way to unlock the bootloader on my Galaxy S5, and have come up short (there is a way to change the CID on the internal storage so that the phone thinks it's a 'developer edition' device, but mine is incompatible.

**Comment by feherneoh** [comment]
The custom UEFI on these devices is just chainloaded from the stock firmware, so it requires the stock bootloader to be unlocked for it to work.

**Comment by imbushuo** [comment]
@0x0000ff First there are concepts here:

- OEM unlock [Android]: allows you to run some customized kernel
- Linux ARM/AArch64 Boot Protocol: basically, it defines the expected processor state, memory config, register usage upon the kernel entry
- BootShim: github.com/imbushuo/BootShim which is self-explanatory

I don't want to spend much time explaining the QCOM WP UEFI security vuln here. Our firmware chainloads from the QCOM and OEM firmware. You need to get the capability of running something in at least EL1, and the developer unlock is an option. Then you need to have binary ready at specific memory address (for AArch64 Linux it is memory_base + 0x80000 typically.) You can ignore content in registry x0 unless you need access to the stock device tree.

**Comment by 0x0000ff** [comment]
Thanks. I appreciate this.
